name: Playwright E2E Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  playwright:
    name: 'Playwright E2E Tests'
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright/python:v1.37.0-jammy
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install app dependencies
        run: |
          npm install
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install test dependencies
        run: |
          cd e2e
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install
      - name: Run app locally
        run: |
          npm run dev &> /dev/null
      - name: Run E2E tests
        run: |
          cd e2e
          xvfb-run pytest
      - name: Upload HTML report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report
          path: e2e/report.html
      - name: Upload Playwright traces
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: playwright-traces
          path: e2e/test-results
